In [ ]:
import numpy as np
import pandas as pd

import torch
import torch.nn as nn

## 역전파 - 가중치 업데이트

In [ ]:
torch.manual_seed(1017)

inputs = torch.randn(2,2) # 2행 2열짜리 데이터를 생성
inputs

tensor([[-0.4318,  0.0749],
        [-0.1667, -1.6542]])

In [ ]:
torch.manual_seed(777)
targets = torch.randn(2) # label 생성
targets

tensor([-0.4015, -0.5934])

In [ ]:
torch.manual_seed(1017)

total_network = nn.Sequential(
    nn.Linear(2,1),
    nn.Sigmoid()
    )

total_network[0].weight

Parameter containing:
tensor([[0.4371, 0.3060]], requires_grad=True)

In [ ]:
# 역전파에 필요한 요소들을 설정
learning_rate = 0.001
criterion = nn.MSELoss(); # LOSS 함수 정의 : MSE
optimizer = torch.optim.Adam(total_network.parameters(), lr = learning_rate)

In [ ]:
total_network.train()
pred = total_network(inputs)
print(pred)

loss = criterion(targets, pred)
print(loss)

tensor([[0.5068],
        [0.4047]], grad_fn=<SigmoidBackward0>)
tensor(0.9203, grad_fn=<MseLossBackward0>)


/usr/local/lib/python3.7/dist-packages/torch/nn/modules/loss.py:530: UserWarning: Using a target size (torch.Size([2, 1])) that is different to the input size (torch.Size([2])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


In [ ]:
loss.backward() # loss값을 참고해서 각 가중치에 대해서 편미분을 하겠다.
optimizer.step() # 편미분된 값과 미리 지정한 학습률을 통해 한 스템 최적화 진행

In [ ]:
total_network[0].weight

# 가중치(weight) 가 업데이트 된 것을 확인할 수 있다.

Parameter containing:
tensor([[0.4381, 0.3070]], requires_grad=True)

In [ ]:
pred = total_network(inputs)
print(pred)

loss = criterion(targets, pred)
print(loss)

tensor([[0.5064],
        [0.4040]], grad_fn=<SigmoidBackward0>)
tensor(0.9193, grad_fn=<MseLossBackward0>)


/usr/local/lib/python3.7/dist-packages/torch/nn/modules/loss.py:530: UserWarning: Using a target size (torch.Size([2, 1])) that is different to the input size (torch.Size([2])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
